# Generated by Django 5.0.6 on 2024-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('project_category', models.CharField(choices=[('Website Development', 'Website Development'), ('E-commerce Site', 'E-commerce Site'), ('Web Application', 'Web Application'), ('UI/UX Design', 'UI/UX Design'), ('Landing Page Design', 'Landing Page Design')], max_length=50)),
                ('budget_range', models.CharField(choices=[('KES 10,000 - KES 25,000', 'KES 10,000 - KES 25,000'), ('KES 25,000 - KES 50,000', 'KES 25,000 - KES 50,000'), ('KES 50,000 - KES 100,000', 'KES 50,000 - KES 100,000'), ('KES 100,000+', 'KES 100,000+')], max_length=50)),
                ('project_description', models.TextField()),
                ('timeline', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
