# Generated by Django 5.2.8 on 2025-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_technology_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('design', 'Design'), ('video', 'Video')], max_length=20),
        ),
    ]
