# Generated by Django 5.2.8 on 2025-11-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('design', 'Design'), ('analysis', 'Analysis')], max_length=20),
        ),
    ]
